/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/items-to-review/': RouteRecordInfo<'/items-to-review/', '/items-to-review', Record<never, never>, Record<never, never>>,
    '/pacttos-chats/': RouteRecordInfo<'/pacttos-chats/', '/pacttos-chats', Record<never, never>, Record<never, never>>,
    '/personal-information/': RouteRecordInfo<'/personal-information/', '/personal-information', Record<never, never>, Record<never, never>>,
    '/reference-video-library/': RouteRecordInfo<'/reference-video-library/', '/reference-video-library', Record<never, never>, Record<never, never>>,
    '/review-packages-for-sale/': RouteRecordInfo<'/review-packages-for-sale/', '/review-packages-for-sale', Record<never, never>, Record<never, never>>,
    '/review-settings/': RouteRecordInfo<'/review-settings/', '/review-settings', Record<never, never>, Record<never, never>>,
    '/web-links-you-created/': RouteRecordInfo<'/web-links-you-created/', '/web-links-you-created', Record<never, never>, Record<never, never>>,
  }
}
